language: node_js
node_js:
  - 11
os:
  - linux
  - osx
  - windows
script: npm run ci-test
cache: npm
env:
  global: COVERALLS_PARALLEL=true
notifications:
  email: false
  webhooks: https://coveralls.io/webhook
