language: node_js
node_js:
  - 11
os:
  - linux
  - osx
  - windows
script: npm run ci-test
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
# Deployment must happen after tests for the whole matrix have been performed,
# so we use `jobs.include` with a different `stage`
jobs:
  include:
    - stage: Deploy
      # We have already run tests
      script: skip
      # We want to run install step and keep built files for release
      skip_cleanup: true
      if: tag is not blank
      # We run `release-it` locally (which tagged the commit and create a
      # GitHub release) but we publish to npm only after CI success.
      deploy:
        provider: npm
        email: ehmicky@gmail.com
        on:
          tags: true
cache: npm
# This merges all LCOV files into one before sending to Coveralls, allowing
# code coverage percentage to include OS/environment-specific coverage.
env:
  global: COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
  email: false
