language: node_js
node_js:
  - 11
os:
  - linux
  - osx
  - windows
script: npm run ci-test
jobs:
  include:
    - stage: Deploy
      script: skip
      deploy:
        provider: npm
        email: ehmicky@gmail.com
        api_key:
          secure: 'HGXkllgDvBpKufrSY73j9u2QqEm0aiKXpyLQ4DvwPTaOlFnWWe74j+eiNJvpdKoRoi9CZQGFnaO0ngzOUfGgxP5fa0N1Gt5Pjiwr2dcqsKgkN1OMozzkS8Wzzwtpulfs7hUdfydqjo0P+5A9qEPRA1yhn5TFUYompOT1IYZyyS8hJwrn0o516/ZkxzpJI75p3vUv62o+Fnd7RyWeCVKIjzS2lEV3YSsVeixlSFKJ08F7YtlWgwHju5wCkcYvtMH3S1XQz8SFGbnT74XKxb5SnEaIr6j3c4TS6JP0myCZL/t9YlRzPUHCsYRgxAs7IdsHr+eK+SBODHyfzpkBcTErfdyf74AymJu244EFT1jAGMeydq4ZYexrgcftVTPYsdmzSZJgSXoL7ziayXm1qstFmJPQrfcRHag0BEivPHl1nAvS2sstk7YdQQN/1ri39qi9oK24fdL8GQ7kcj9shRHBd2UTZDl8tE/3g0Ujn+iQsUeJ/JFAlaa8hN9SaRGhG/dvdiYAu3lB8ga1aDKNlnHEkR6eR9GCPV8WjbooSNBSHEJC/cGHLzJeeF4By8prshCIBd3iPou6JDtjpyiVa2nOnlFIdU//fDdU0wq6tcp/LxUqYaBpHvU3LpklKVZzUAmipBnlKLgEpgt1sSpuJckTJOY+TWt6T3egYtieLeIiLqk='
        on:
          tags: true
cache: npm
env:
  global: COVERALLS_PARALLEL=true
notifications:
  email: false
  webhooks: https://coveralls.io/webhook
